export const products = [
    {
        id: 1,
        name: "Iphone 11",
        category: "Iphone",
        storage: "128GB",
        price: 567,
        image: "/images/products/11.png",
        isCart: false,
        description: "Rekam video 4K, potret yang indah, dan lanskap yang lebih luas dengan sistem kamera ganda yang sepenuhnya baru. Ambil foto berpencahayaan rendah terbaik dengan mode Malam. Lihat warna yang begitu nyata dalam foto, video, dan game di layar Liquid Retina 6,1 inci. (3) Nikmati performa tak tertandingi dengan A13 Bionic untuk game, augmented reality (AR), dan fotografi. Lakukan lebih banyak hal tanpa perlu sering mengisi daya dengan kekuatan baterai sepanjang hari. (2) Dan nikmati ketenangan dengan ketahanan air hingga 2 meter selama 30 menit.(1)",
    },
    {
        id: 2,
        name: "Iphone 12 Pro Max",
        category: "Iphone",
        storage: "256GB",
        price: 882,
        image: "/images/products/12prmx.png",
        isCart: false,
        description: "iPhone 12 Pro Max. Layar Super Retina XDR 6,7 inci yang lebih besar.1 Ceramic Shield dengan ketahanan jatuh empat kali lebih baik.2 Fotografi pencahayaan rendah yang menakjubkan dengan sistem kamera Pro terbaik di iPhone, dan rentang zoom optik 5x. Mampu merekam, mengedit, dan memutar video sekelas sinema dengan Dolby Vision. Potret mode Malam dan pengalaman AR di level berikutnya dengan LiDAR Scanner. Chip A14 Bionic yang andal. Dan aksesori MagSafe baru untuk kemudahan pemasangan dan pengisian daya nirkabel yang lebih cepat.3 Untuk berjuta kemungkinan spektakuler.",
    },
    {
        id: 3,
        name: "Iphone 13 Pro Max",
        category: "Iphone",
        storage: "512GB",
        price: 1071,
        image: "/images/products/13prmx.png",
        isCart: false,
        description: "iPhone 13 Pro Max. Pembaruan sistem kamera Pro yang terbesar. Layar Super Retina XDR dengan ProMotion untuk penggunaan yang terasa lebih cepat dan responsif. Chip A15 Bionic yang secepat kilat. Desain kokoh dan kekuatan baterai terbaik yang pernah ada di iPhone.",
    },
    {
        id: 4,
        name: "Iphone 14 Pro Max",
        category: "Iphone",
        storage: "1TB",
        price: 1889,
        image: "/images/products/14prmx.png",
        isCart: false,
        description: "iPhone 14 Pro Max. Memotret detail menakjubkan dengan kamera Utama 48 MP. Nikmati iPhone dalam cara yang sepenuhnya baru dengan layar yang Selalu Aktif dan Dynamic Island. Deteksi Tabrakan, sebuah fitur keselamatan baru, memanggil bantuan saat Anda tak bisa.",
    },
    {
        id: 5,
        name: "Xiaomi 13 Ultra",
        category: "Xiaomi",
        storage: "12GB + 512GB",
        price: 955,
        image: "/images/products/13Ultra.png",
        isCart: false,
        description: "Xiaomi 13 Ultra merupakan HP dengan layar 6.73 inci dan tingkat densitas piksel sebesar 552ppi. Ia dilengkapi dengan kamera belakang 50.3 + 50 + 50 + 50MP dan kamera depan 32MP. HP ini juga hadir dengan kapasitas baterai 5000mAh.",
    },
    {
        id: 6,
        name: "Xiaomi 12T",
        category: "Xiaomi",
        storage: '8GB + 256GB',
        price: 378,
        image: "/images/products/xiaomi12t.png",
        isCart: false,
        description: "Ciptakan momen mega! Memperkenalkan Xiaomi 12T dengan kamera kelas pro 108MP, MediaTek Dimensity 8100-Ultra, 120W HyperCharge, dan layar AMOLED CrystalRes 120Hz.",
    },
    {
        id: 7,
        name: "Xiaomi 11T",
        category: "Xiaomi",
        storage: '8GB + 256GB',
        price: 315,
        image: "/images/products/xiaomi11t.png",
        isCart: false,
        description: "Xiaomi 11T menghadirkan pengalaman sinematik terbaik, Dilengkapi dengan kamera pro-grade 108MP, layar AdaptiveSync AMOLED 120Hz, pengisian turbo kabel 67W, serta Dolby Atmos kelas bioskop.",
    },
    {
        id: 8,
        name: "Xiaomi 11 Ultra",
        category: "Xiaomi",
        storage: '12GB + 256GB',
        price: 1071,
        image: "/images/products/xiaomi11ultra.png",
        isCart: false,
        description: "Dengan sensor super besar 1/2” dan 48MP, kamera beresolusi tinggi telefoto memanfaatkan potensi yang lebih besar. Setelah zoom beberapa kali, pemandangan yang jauh tetap terlihat jernih dan jelas.",
    },
    {
        id: 9,
        name: "Realme GT Neo 5 SE",
        category: "Realme",
        storage: '256GB',
        price: 10,
        image: "/images/products/realmegtneo5se.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 10,
        name: "Realme 11 Pro+ 5G",
        category: "Realme",
        storage: '512GB',
        price: 10,
        image: "/images/products/realme11pro+5g.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 13,
        name: "Realme 9 Pro",
        category: "Realme",
        storage: '512GB',
        price: 10,
        image: "/images/products/realme9pro.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 14,
        name: "Realme GT Master Edition",
        category: "Realme",
        storage: '512GB',
        price: 10,
        image: "/images/products/realmegtmaster.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 11,
        name: "Samsung Galaxy S23 FE",
        category: "Samsung",
        storage: '128GB',
        price: 10,
        image: "/images/products/samsungs23fe.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 12,
        name: "Samsung Galaxy S23 Ultra",
        category: "Samsung",
        storage: '256GB',
        price: 10,
        image: "/images/products/samsungs23ultra.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 15,
        name: "Samsung Galaxy S23 5G",
        category: "Samsung",
        storage: '256GB',
        price: 10,
        image: "/images/products/samsungs23.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
    {
        id: 16,
        name: "Samsung Galaxy S23+ 5G",
        category: "Samsung",
        storage: '256GB',
        price: 10,
        image: "/images/products/samsungs23+.png",
        isCart: false,
        description: "White Casual Short Sleeve Cotton Plain Top Embellished Non-Stretch Summer Men Tops",
    },
];